### ISSUE TITLE
Bug: Changing formatting doesn't update the form value unless you change the text after

### ISSUE THREAD

**Issue by sean-douglass** [kolkov/angular-editor#122] opened 2019-08-01 21:31 UTC
If you enter text into the angular-editor control and view the value in the form object, you will see the text (using a submit action). If you then highlight some of the text and bold it, but don't the text at all and check the value, the bold tags will not be there (this applies to changing any formatting). If you change the text and try it again, the bold or formatting tags will show up.

Using the demo app linked from this projects main page you can repo this issue. Open the example link on this projects home page. Type: "This is text." or anything else. Notice the HTML output says: "This is text." as expected. Highlight "text" and click bold. Notice the HTML Output doesn't change. Add a space to the end of the sentence and the bold tags appear.

**Comment by kolkov** [comment] 2019-08-01 22:31
@sean-douglass can't reproduce this bug at https://angular-editor.kolkov.ru/

**Comment by sean-douglass** [comment] 2019-08-01 22:33
I just texted in firefox and it works fine. I guess its only an issue in Edge.

**Comment by kolkov** [comment] 2019-08-01 22:43
Thanks! Confirmed for EDGE browser.

**Comment by alfredosalzillo** [comment] 2019-08-05 13:45
The problem can be solved using the MutationObserber API instead of the input event.

**Comment by kolkov** [comment] 2019-08-05 18:55
@alfredosalzillo I will try to verify your solution. Thanks!

**Comment by kolkov** [comment] 2019-11-16 17:49
I close this issue due to EDGE migrate to Chromium.

**Closed by kolkov** 2019-11-16 17:49 UTC
Labels: bug
