### ISSUE TITLE
Cannot set property 'id' of undefined

### ISSUE THREAD

**Issue by elementalPRESS** [kolkov/angular-editor#131] opened 2019-08-09 11:04 UTC
Hi,

I have updated the editor from version 0.15.4  to  0.18.4. When I start now my application I get this stack:

`TypeError: Cannot set property 'id' of undefined`
`    at AngularEditorComponent.configure (kolkov-angular-editor.js:1069)`
`    at AngularEditorComponent.ngAfterViewInit (kolkov-angular-editor.js:800)`
`    at callProviderLifecycles (core.js:26694)`
`    at callElementProvidersLifecycles (core.js:26659)`
`    at callLifecycleHooksChildrenFirst (core.js:26641)`
`    at checkAndUpdateView (core.js:37060)`
`    at callViewAction (core.js:37416)`
`    at execEmbeddedViewsAction (core.js:37373)`
`    at checkAndUpdateView (core.js:37051)`
`    at callViewAction (core.js:37416)`
`    at execEmbeddedViewsAction (core.js:37373)`
`    at checkAndUpdateView (core.js:37051)`
`    at callViewAction (core.js:37416)`
`    at execComponentViewsAction (core.js:37344)`
`    at checkAndUpdateView (core.js:37057)`

I have two editors on my side. They are configured like:

`<angular-editor id="editor2" class="w-100 border0" [config]="editorConfig" [(ngModel)]="message.content"></angular-editor>`

`<angular-editor id="editor1" class="w-100 border0" [config]="editorConfig" [(ngModel)]="message.contentReply"></angular-editor>`

Pls help.

best wishes,
Lars

**Comment by elementalPRESS** [comment] 2019-08-09 11:15
I could terminate this error message by coping the config from the demo to my project. Any of the new options (the missing of any option, resp.) is producing this error.

But now there is a new one: in general I'm using the same code as provided in the demo. The editor opens and everything looks fine. BUT: I'm unable to write text. The textarea is not editable and non of the buttons can be clicked...

What is happen? It was such a nice editor but the last update makes so many problems :-(

**Comment by kolkov** [comment] 2019-08-09 11:42
Hi! Thanks for your report.
The first breakdown was due to the fact that now you can choose the location of the toolbar.  The first option is without a toolbar at all, either from above or from below.  I think that by default we need to make a choice of standard mode.

**Comment by kolkov** [comment] 2019-08-09 11:44
Please provide demo with reproduction of this problem at stackblitz.

**Comment by weyandch** [comment] 2019-08-22 09:45
Hi @kolkov 
I ran into the same problem when updating the angular-editor in my project.

I've been missing the new attribute
`toolbarPosition: 'top'`
from my editorConfig, i think it would be convenient to asume "top" as default?

**Comment by zijianhuang** [comment] 2019-08-26 00:18
Much improvements fantastic in this release. Yes, "top" as default is even better so existing apps won't be broken.

**Comment by kolkov** [comment] 2019-08-26 09:35
@zijianhuang this fixed in 1.0.0-beta.1 thanks! Try new build if you ar on Angular 8.x.x already.

**Closed** 2019-09-06 09:17 UTC
